apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: controller
  newName: ghcr.io/phoban01/ocm-controller
  newTag: latest
- name: open-component-model/ocm-controller
  newName: localhost:5001/open-component-model/ocm-controller
  newTag: v0.0.1
