{{- if .Values.generateTlsCert }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocm-registry-tls-certs
  namespace: sap-ocm-controller
spec:
  secretName: ocm-registry-tls-certs
  dnsNames:
    - registry.sap-ocm-controller.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: ocm-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ocm-certificate-issuer
spec:
  ca:
    secretName: ocm-registry-tls-certs
{{- end}}