# permissions for end users to edit actions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: action-editor-role
rules:
- apiGroups:
  - ocmcontroller.ocm.software
  resources:
  - actions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocmcontroller.ocm.software
  resources:
  - actions/status
  verbs:
  - get
