# permissions for end users to view actions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: action-viewer-role
rules:
- apiGroups:
  - ocmcontroller.ocm.software
  resources:
  - actions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocmcontroller.ocm.software
  resources:
  - actions/status
  verbs:
  - get
