# permissions for end users to edit componentversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentversion-editor-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions/status
  verbs:
  - get
