# permissions for end users to view componentversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocmcomponent-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions/status
  verbs:
  - get
