# permissions for end users to edit componentdescriptors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentdescriptor-editor-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentdescriptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentdescriptors/status
  verbs:
  - get
