# permissions for end users to view componentdescriptors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentdescriptor-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentdescriptors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentdescriptors/status
  verbs:
  - get
