# permissions for end users to view fluxdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fluxdeployer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocm-controller
    app.kubernetes.io/part-of: ocm-controller
    app.kubernetes.io/managed-by: kustomize
  name: fluxdeployer-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - fluxdeployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - fluxdeployers/status
  verbs:
  - get
