# permissions for end users to edit localizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localization-editor-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - localizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - localizations/status
  verbs:
  - get
