# permissions for end users to view localizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localization-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - localizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - localizations/status
  verbs:
  - get
