# permissions for end users to view ocmcomponentversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocmcomponent-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - ocmcomponentversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - ocmcomponentversions/status
  verbs:
  - get
