---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - actions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - actions/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - actions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - componentversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - resources/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - resources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - sources/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - sources/status
  verbs:
  - get
  - patch
  - update
