apiVersion: delivery.ocm.software/v1alpha1
kind: Action
metadata:
  name: localize
  namespace: wge-system
spec:
  componentRef:
    name: wge
    namespace: wge-admin
  sourceRef:
    name: wge-admin-source
  providerRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Localization
    name: wge-localizer
status:
  ready: true
  snapshot: string