apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: podinfo-manifests
spec:
  interval: 10m0s
  componentVersionRef:
    name: github.com/phoban01/podinfo
    namespace: default
  resource:
    name: manifests
    referencePath:
      - name: installer
  snapshotTemplate:
    name: podinfo-manifests
    tag: latest
