apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: podinfo
spec:
  interval: 10m
  sourceRef:
    kind: Snapshot
    name: carts-manifests
    namespace: default
  configRef:
    componentVersionRef:
      name: nested-component
      namespace: default
    resource:
      name: config
      referencePath:
        name: carts
  snapshotTemplate:
    name: carts-manifests-localized
    tag: latest
