apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: deployment
spec:
  interval: 10m0s
  sourceRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: manifests
  configRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: config
