apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: monolith
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: "1674356"
  insecure: true
  url: oci://registry.ocm-system.svc.cluster.local:5000/sha-11414808128353696106
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monolith
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: monolith
