name: e2e

on:
  pull_request:
    paths-ignore:
      - 'CODE_OF_CONDUCT.md'
      - 'README.md'
      - 'Contributing.md'

  push:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  kind-linux:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/open-component-model/ocm-e2e-framework
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.OCMBOT_APP_ID }}
          private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - name: Configure private module access
        run: |
          git config --global \
            url.https://${{ steps.generate_token.outputs.token }}@github.com/.insteadOf \
            https://github.com/
      - name: Restore Go cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kustomize: '5.0.1'
          tilt: '0.32.2'
      - name: Run E2E tests
        run: make e2e
